skedgo/tripgo-api

tripgo.swagger.yaml
Specs for #33. Not yet deployed to production, so can't yet be merged.
=> location.json variant with coordinate + radius

docs/index.md
brian and i are making updates on skedgo.com
=> link to blog for fastgo

docs/faq.md, docs/specs/tripgo.swagger.yaml
@nighthawk in case you want to check, we updated with @JulietaMarcos the specs and doc. 
We added a new section under `routing` in the faq.
=> update faq and specs

docs/enterprise/push.md, docs/specs/pn.swagger.yaml
Working through adding push notifications to an iOS app using the TripGo API. Made some small adjustments and additions to the push docs.
=> Review + update iOS PN docs

docs/specs/tripgo.swagger.yaml
=> Updated description of `tt` parameter

docs/specs/tripgo.swagger.yaml
Adrian, this matches latest implementation.
=> added missing field in components

docs/specs/tripgo.swagger.yaml
Addresses #84, providing a new "fb" parameter to `routing.json`.
=> Folding bicycle flag

docs/specs/tripgo.swagger.yaml
related to #97 , not sure why this was commented out.
=> uncomment carpod doc

docs/specs/tripgo.swagger.yaml
see [PR](https://github.com/skedgo/skedgo-java/pull/1043)
=> add `includeStops` flag to update trip endpoint

mkdocs.yml
it was there but commented out
=> Add reference to the header

docs/specs/tripgo.swagger.yaml
Please merge this once https://github.com/skedgo/skedgo-java/pull/1144 is in production
=> Update specs for new fields

docs/specs/tripgo.swagger.yaml
=> adding modeInfo doc

docs/faq.md
Adding MapData section to FAQ. Tried to explain that from the platform point of view. Can you review it? Not sure if you prefer that somewhere else.
=> adding Map Data to FAQ

docs/specs/tripgo.swagger.yaml
We have some requests for exposing trip and segments IDs.
@nighthawk are you ok with adding them as documented here?
=> Adding trip and segment unique ids

docs/specs/tripgo.swagger.yaml
=> Adding routing.json errors documentation

docs/specs/tripgo.swagger.yaml
=> Add "bestOnly" param documentation for routing

docs/specs/tripgo.swagger.yaml
docs for [#1354](https://github.com/skedgo/skedgo-java/pull/1354)
=> adding deep link to bike pod info

docs/specs/tripgo.swagger.yaml
=> adding local cost accuracy explanation

docs/specs/tripgo.swagger.yaml
=> adding skedgoify frames description

docs/specs/tripgo.swagger.yaml
=> adding deprecated field to segment templates

INSTRUCTIONS.md
Mariano, please proof read and fix if necessary.
=> Instructions for how to run locally and deploy

docs/specs/tripgo.swagger.yaml
Change from https://github.com/skedgo/skedgo-java/pull/1903
=> Add SegmentReference.timetableEndTime

docs/specs/tripgo.swagger.yaml
Adds (optional) real-time information of predicted and actual times at stops of a service.
=> Actual and timetable time in shapes

docs/specs/tripgo.swagger.yaml
Updated API docs for https://github.com/skedgo/skedgo-java/pull/1954
=> Updated API docs for public transport blacklists and whitelists (#12145)

docs/specs/tripgo.swagger.yaml
(Also remove now defunct 'ir' parameter.)
=> Adds 'wm' parameter

docs/extensions.md
Adding TSP connectors explanation
=> work on TSP connectors docs

docs/extensions.md
Adding new region creation explanation
=> New region extension docs

docs/specs/tripgo.swagger.yaml
- Adding deep links to sharedVehicle output
- Adding deep link to AppInfo
=> Feature/14265rental URIs

docs/specs/tripgo.swagger.yaml
* New optional parameter `cityPolygons` in `regions.json` added.
* `City` now contains `identifier` and `boundaries`.
* `Location` now has a `City` identifier.
=> City boundaries

docs/specs/tripgo.swagger.yaml
for change [#3992](https://github.com/skedgo/skedgo-java/pull/3992)
=> adding accessibilityLabel

docs/specs/tripgo.swagger.yaml
See diff from YAML for details.
=> New real-time vehicle position fields

docs/specs/tripgo.swagger.yaml
Docs related to https://github.com/skedgo/skedgo-java/pull/4667
=> Updated docs for new cycle tags (RM 16049)

docs/specs/tripgo.openapi.yaml
=> Documentation for new etwt[] parameter

docs/specs/tripgo.openapi.yaml
Docs for https://github.com/skedgo/skedgo-java/pull/5646
=> Updated docs for new amopt routing.json parameter

docs/specs/tripgo.openapi.yaml
Documentation for: https://redmine.buzzhives.com/issues/18783
=> Updated docs for safe walking tags 

docs/specs/tripgo.openapi.yaml
Docs for https://redmine.buzzhives.com/issues/19343
=> Updated docs for custom speeds 

docs/specs/tripgo.openapi.yaml, docs/specs/tripgo.swagger.yaml
CarParkInfo updated: 
- Added booleans to identify the park-and-ride and kiss-and-ride car parks.
=> 20907: park-and-ride and kiss-and-ride support added

docs/specs/tripgo.openapi.yaml, docs/specs/tripgo.swagger.yaml
- Redmine: https://redmine.buzzhives.com/issues/21423
- Skedgo-java PR: https://github.com/skedgo/skedgo-java/pull/6803
- Added the new “neverAllowFeeds” and “onlyAllowFeeds” restrictions.
- Fixed types in the descriptions.
=> Feed restrictions added

docs/specs/modules/booking.definitions.yaml, docs/specs/tripgo.openapi.yaml
https://redmine.buzzhives.com/issues/21900
=> Error code documentation
