skedgo/tripgo-api

- tripgo.swagger.yaml
`locationInfo.json` now has details for:
- Bike pods
- Car share pods (not finalised)
- Car parks (not finalised)
- Car rental
`locations.json` now has modes input and `bikePods, `carPods`, `carParks` and `carRental` output that's using the same data model to `locationInfo.json`.
> More location info

- tripgo.swagger.yaml
New indicator for availability (issues) of a trip or its segments.
Should only be merged once those new properties are reflected in all production servers (https://github.com/skedgo/skedgo-java/pull/505).
> Adding availability to trip and segment

- tripgo.swagger.yaml
1. Added `TripGroup.sources`
2. Deprecated `SegmentTemplateMovingTransit.disclaimer`
> Source attribution for trip groups

- tripgo.swagger.yaml
New `includeStops` input to `routing.json`. With this endabled, the shapes for templates will include a list of stops and the relative departure and arrival times.
> New includeStops input to routing.json

- docs/specs/tripgo.swagger.yaml
- Added description of the new `localCost` field
- Deprecated the old `cost` field
- Fixed issue when displaying `sources` inside segment templates
The new field isn't yet deployed. @MarianoTucat can you merge this after the next deploy of production code, if @nighthawk approves these changes?
> Updated api docs with the new `localCost` field.

- docs/specs/tripgo.swagger.yaml
This adds a field called `specificModes` with three lists:
- `public_transport`
- `taxi_and_tnc`
- `shared_vehicles`
currently, all three have the same structure, but may differ in the future.
java changes in [PR](https://github.com/skedgo/skedgo-java/pull/940)
> specificModes field in regionInfo.json

- docs/specs/tripgo.swagger.yaml
to disable two way hires including return costs (enabled by default)
> add new routing.json flag `2wirc`

- docs/specs/tripgo.swagger.yaml
With an upcoming update of the TripGo API in mid April 2018, cycling segments will include "push your bike" sections. This change is made to address user and developer feedback of missing cycling and cycling + public transport results, that were due to those paths requiring small sections where cycling is not allowed and the cyclist will have to push/carry their bicycle.
Two changes:
1. Cycling segments will now use those sections (but will avoid them and only do so if no other route around them makes sense)
2. Those sections will be marked with `dismount` in the segment's `street` array, and the segments themselves will have the total `metresDismount` in them.
Our recommendation: Update your UIs so that they display these parts however it makes sense (e.g., colour them red or replace …
> Cycling segments include push-your-bike sections

- docs/enterprise/push.md
- docs/faq.md
- docs/index.md
- docs/specs/account.swagger.yaml
- docs/specs/bookings.swagger.yaml
- docs/specs/modules/account.definitions.yaml
- docs/specs/modules/account.paths.yaml
- docs/specs/modules/booking.definitions.yaml
- docs/specs/modules/booking.paths.yaml
- docs/specs/pn.swagger.yaml
- docs/specs/tripgo.swagger.yaml
- docs/specs/user.swagger.json
- docs/swagger/index.html
removing hardcoded urls so we can deploy the specs both in:
- https://developer.tripgo.com/
- https://developer-beta.tripgo.com/ (beta only)
@nighthawk wdyt of having a beta/dev only specs/docs site?
> dynamic urls

- docs/specs/tripgo.swagger.yaml
This PR switches all times (and other fields that also apply) to use integer instead of number, to be consistent.
> times using integer instead of number

- docs/faq.md
- docs/specs/tripgo.swagger.yaml
Adds a parameter to `routing.json` which does the following:
> By default, when sending more than one mode only results for trips mixing at least two of those modes are returned and trips using a single-mode are omitted. Set this parameter to `true` to change this behaviour, so that all trips are returned - regardless of the number of modes used.
Actions:
> Add 'allModes' parameter

- docs/faq.md
- docs/specs/tripgo.swagger.yaml
This updates the documentation for a recent change to the TripGo API:
- ModeInfo.identifier is no longer optional
- Documentation of `stationary_` identifiers
> Stationary identifiers

- docs/specs/tripgo.swagger.yaml
- Remove `arrivals.json` from specs as that doesn't exist
- Remove two properties from `service.json` from the root level, as they are provided on the shapes level further down instead.
> Swagger cleanup

- docs/specs/tripgo.swagger.yaml
- Added `ModeInfo.remoteIconIsBranding`
- Added `ModeIdentifier.subtitle`
- Added `SpecificModeDetails.modeImageNames`
These will be added with https://github.com/skedgo/skedgo-java/pull/1463
> Documented new fields related to micro-mobility modes

- docs/specs/tripgo.swagger.yaml
Main changes:
- Update `segment.sharedVehicle` for trip planning results
- Changes model to `SharedVehicle`
- Removes old model `Vehicle` from specs
- Note: This no longer provided for moving segments, but added to stationary "collect" segments
- Adds `freeFloating` vehicles to `locations.json` specs
Also:
- Review Service model, adding `operatorID` and `serviceTextColor`
> Shared vehicle additions

- docs/specs/tripgo.swagger.yaml
Since it's now a number, not an integer (e.g. we support `tt=0.5` to specify 30 seconds).
> Adjusted documentation for `tt` parameter

- docs/specs/tripgo.swagger.yaml
Adds:
- `stop.zoneID`
- `segment.operatorID`
- `ticket.fareID`
- `trip.currency`
Also:
- Remove segment.serviceOperator (still provided, but should use operator)
- Minor optionality / description review
> Add more ticket/fare related information

- docs/specs/tripgo.swagger.yaml
Updated documentation for new routing.json parameters: 
- `rtdr` and `etwt` (https://github.com/skedgo/skedgo-java/pull/2216)
- `neverAllowModes` (https://github.com/skedgo/skedgo-java/pull/2229)
> Updated docs for new parameters

- docs/specs/tripgo.swagger.yaml
Only provided in New South Wales, Australia, currently.
> Add optional `RealTimeVehicle.Components.occupancyText`

- docs/specs/modules/booking.definitions.yaml
Adds input field to action (on confirmed field of booking field for a segment where booking is possible)
If present, the `internalURL` will require a POST instead of a GET to trigger the action.
And an object with a field names `input` is required, with the list of input actions returned.
> Action new input field

- docs/faq.md
- docs/specs/tripgo.swagger.yaml
API docs for new `me_mic` mode + `micVehicleType` parameter, and deprecated `cy_bic`.
> Update API specs and FAQ for new micro-mobility modes

- docs/specs/tripgo.swagger.yaml
`shortName` is still in the API but undocumented and will be removed later.
> Rename shortName to platformCode

- docs/index.md
- mkdocs.yml
Updates home page and navigation to include React SDK.
(Also removes mention of FastGo as that's quite old and not maintained.)
> Add link to React SDK

- docs/specs/tripgo.openapi.yaml
Also:
- Rename the `/info` endpoints to be plural as they return lists: `route.json` to `routes.json`, `operator.json` to `operators.json` and `service.json` to `services.json`
- Group public transport endpoints under "Public Transport"
- Fix some typos
> `/info/routes.json` can now return routes for all operators

- docs/specs/tripgo.openapi.yaml
This adds a `geofences` array to trip segments, which can then be used by the frontend to set-up appropriate geofences for a trip. That way, we can make sure the logic is the same on iOS and Android, and we can also update and tweak it dynamically.
> API spec proposal for geofence information

- docs/specs/tripgo.openapi.yaml
- docs/specs/tripgo.swagger.yaml
Redmine: [22751: Adjust info/*.json endpoints to a list of regions](https://redmine.buzzhives.com/issues/22751)
Satapp PR: https://github.com/skedgo/skedgo-java/pull/7211
> 22751: add the `regions` definition in the info/*.json endpoints

- docs/specs/tripgo.openapi.yaml
- docs/specs/tripgo.swagger.yaml
Add the “externalData” cases with the “stop_id” for the GTFS sources
> 24212: Display GTFS stop_id in the external data
